### ISSUE TITLE
fileServersNG SMB Kerberos - [FileSrvWorker12] [T1:2] Error processing security blob - java.lang.NullPointerException

### ISSUE THREAD

**Issue by wclemo** [FileSysOrg/fileServersNG-v61#2]
Please note that this document is edited from original post. I apologies for any confusion this might have caused.

I am testing Kerberos SMB authentication. When trying to browse the _\\\alfresco-host\alfresco_ share I am bumping into the error listed above.

Also, on another note, after going through the kerberos entries, I noticed that there is one entry that might be missing (or not needed ?). This is the kerberos authentication password entry. The original Alfresco CIFS entry is as follows:

**kerberos.authentication.cifs.password=XXXX**

I couldnt find the equivalent one for the SMB config. Is it not required ?

My config for Kerberos is as follows:

= **alfresco-global.properties**

_authentication.chain=kerberos1:kerberos,alfrescoNtlm1:alfrescoNtlm_

#**SMB server related properties**
smb.enabled=true
smb.serverName=alf6
smb.domain=acme.com
smb.broadcast=auto

smb.tcpipSMB.port=1445
smb.netBIOSSMB.sessionPort=1139
smb.netBIOSSMB.namePort=1137
smb.netBIOSSMB.datagramPort=1138

smb.bindto=
smb.ipv6.enabled=false
smb.hostannounce=true

smb.disableNTLM=false
smb.disallowNTLMv1=true
#smb.useSPNEGO=false
smb.useSPNEGO=true

#**fileServersNG SMB kerberos authentication**
alfresco.authentication.authenticateCIFS=true
smb.kerberos.realm=ACME.COM
smb.kerberos.stripUsernameSuffix=true
smb.kerberos.loginEntryName=FileServerSMB
smb.kerberos.debug=true

==The logs

 _2019-06-28 12:25:06,258  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker10] [T1:2] Negotiated SMB v2 dialect - SMB 2.210
 2019-06-28 12:25:06,468  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker11] [SMB] Process security blob=[SPNEGO secBlob=[offset=92,len=74] Unicode, respBlob=null]
 2019-06-28 12:25:06,474  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker11] [SMB] Received NTLM Type1/Negotiate - [Type1:0xe2088297,Domain:<NotSet>,Wks:<NotSet>]
 2019-06-28 12:25:06,475  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker11] [SMB] Signing required/SPNEGO, saved Type1
 2019-06-28 12:25:06,484  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker11] [SMB] Two stage logon (SPNEGO)
 2019-06-28 12:25:06,485  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker11] [T1:2] Process security blob returned sts=MORE_PROCESSING
 2019-06-28 12:25:06,485  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker11] [T1:2] Session setup secBlob=[SPNEGO secBlob=[offset=92,len=74] Unicode, respBlob=159bytes]
 2019-06-28 12:25:06,488  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker12] [SMB] Process security blob=[SPNEGO secBlob=[offset=92,len=429] Unicode, respBlob=null]
 2019-06-28 12:25:06,493  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker12] [SMB] Received NTLM Type3/Authenticate - [Type3:,LM:000000000000000000000000000000000000000000000000,NTLM:ed6675ddbe7cca79fd0332e6708d33480101000000000000f0db9b5f932dd50155e69cdec5891a2c000000000200080041004c00460036000100080041004c00460036000400080061006c00660036000300080061006c006600360007000800f0db9b5f932dd501060004000200000008003000300000000000000001000000002000003d6bbc9998441d3ae9782c3d338804ac141e5b8528639f57c3b32c8f1286feda0a001000000000000000000000000000000000000900240063006900660073002f0061006c00660036002e006600690062006f002e0063006f006d00000000000000000000000000,Dom:ACME,User:topcat,Wks:7B,SessKey:d8188e4d62262f9f92403609f05f1d9f,Flags:0x62888015]
 2019-06-28 12:25:06,493  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker12] [SMB] Signing required/SPNEGO, saved Type3
 2019-06-28 12:25:06,619  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker12] [T1:2] Error processing security blob - java.lang.NullPointerException
 2019-06-28 12:25:06,620  ERROR [org.alfresco.fileServersNG] [FileSrvWorker12] Error from JFileServer
 java.lang.NullPointerException_
        _at org.alfresco.repo.security.authentication.MD4PasswordEncoderImpl.decodeHash(MD4PasswordEncoderImpl.java:134)_
        _at org.filesys.alfresco.auth.UsersInterfaceBean.getUserAccount(UsersInterfaceBean.java:247)
        at org.filesys.server.auth.SMBAuthenticator.getUserDetails(SMBAuthenticator.java:781)
        at_ _org.filesys.server.auth.EnterpriseSMBAuthenticator.doNTLMv2Logon(EnterpriseSMBAuthenticator.java:1461)_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.doNtlmsspSessionSetup(EnterpriseSMBAuthenticator.java:944)_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.doSpnegoSessionSetup(EnterpriseSMBAuthenticator.java:1031)_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.processSecurityBlobInternal(EnterpriseSMBAuthenticator.java:775)_
        _at org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator$4.execute(AlfrescoSMBAuthenticator.java:838)
        at org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator$4.execute(AlfrescoSMBAuthenticator.java:833)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
        at org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator.doInTransaction(AlfrescoSMBAuthenticator.java:815)
        at org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator.processSecurityBlobInTransaction(AlfrescoSMBAuthenticator.java:832)
        at org.filesys.server.auth.EnterpriseSMBAuthenticator.processSecurityBlob(EnterpriseSMBAuthenticator.java:731)_
        _at org.filesys.smb.server.a.e.b(Unknown Source)
        at org.filesys.smb.server.a.e.runProtocol(Unknown Source)
        at org.filesys.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1261)
        at org.filesys.smb.server.nio.NIOSMBThreadRequest.runRequest(NIOSMBThreadRequest.java:130)
        at org.filesys.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:136)
        at java.lang.Thread.run(Thread.java:748)_
_2019-06-28 12:25:06,631  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker13] Error during packet receive, closing session sess=T1, addr=10.0.10.24 ex=Connection reset by peer_

**Comment by FileSysOrg** [comment]
Sorry about the delay, didn't get any notification from Github about this new issue either.

The password setting is still available with the fileServersNG settings but is now optional as newer Java versions don't seem to need it.

I'll have to test this one, the client is using NTLM to logon. When I tested Kerberos authentication I did not change the Alfresco authentication chain, the fileServersNG authentication is standalone now.

**Comment by wclemo** [comment]
> 
> 
> Sorry about the delay, didn't get any notification from Github about this new issue either.
> 
> The password setting is still available with the fileServersNG settings but is now optional as newer Java versions don't seem to need it.
> 
> I'll have to test this one, the client is using NTLM to logon. When I tested Kerberos authentication I did not change the Alfresco authentication chain, the fileServersNG authentication is standalone now.

Hello.

I trust that you are well.
It looks like you've been pretty busy of late.  This is just a soft nudge to test and hopefully fix the kerberos fileServersNG authentication. 

Thanks in advance

**Comment by FileSysOrg** [comment]
Hi,

I have a few fixes in the pipeline, just finishing off testing some other issues, then I can get a new fileServersNG release out, later this week hopefully.

**Comment by FileSysOrg** [comment]
I've updated the JFileServer code and fileServersNG to the latest versions.

**Comment by wclemo** [comment]
Thanks for your efforts. Unfortunately, I am running into exactly the very same errors as above when doing Kerberos. My config is also just as above. Am wondering whether there is something else that I might have missed out. 

I have confirmed that the amp installed is the new version 1.0.1. 
Also I have tried with both _smb.useSPNEGO=false_ and _=true_, as well as alternating _authentication.chain=kerberos1:kerberos_  with  _kerberos1:kerberos,alfrescoNtlm1:alfrescoNtlm_.

The startup is fine, but as soon as I browse _\\alfresco-host\alfresco_ share it throws the error before bringing the endless domain login prompts. Whenever I enter the logins it also throws the same errors.

Am really hoping for a successful resolution to this issue.

Regards.

**Comment by FileSysOrg** [comment]
I had another look at the stacktrace you posted earlier, the client is trying to do an NTLM logon rather than Kerberos. It may be the authentication.chain setting that is the problem, have you tried without that setting ?. What happens if you put 'alfrescoNtlm1;alfrescoNtlm' at the start of the authentication chain ?.

I'll do some investigation here, see if I can reproduce it.

**Comment by wclemo** [comment]
> 
> 
> I had another look at the stacktrace you posted earlier, the client is trying to do an NTLM logon rather than Kerberos. It may be the authentication.chain setting that is the problem, have you tried without that setting ?. What happens if you put 'alfrescoNtlm1;alfrescoNtlm' at the start of the authentication chain ?.
> 
> I'll do some investigation here, see if I can reproduce it.


I have tried the other two options, ie with authentication chain starting with 'alfrescoNtlm1;alfrescoNtlm' and also with authentication chain disabled. Am getting the same error as above .

Another thing I noticed is that when the Domain user first types the url \\alfresco_host\alfresco, fileServersNG quickly starts throwing logs before even pressing Enter. It picks the Domain username of the logged on Windows user but indicates that the user is "unknown". When it then brings the logon prompt and you insert a domain user, it this time throws the exact above error.

When I disabled the authentication chain, the startup of fileServersNG has a very descriptive smb kerberos authentication log as opposed to when it is enabled. The same happens with HTTP kerberos log anyway.

Below are two logs, first is  for I type \\alfresco_host\alfresco (before pressing enter), and the second is for fileServersNG, incase it is useful;

 _2019-07-17 14:23:59,569  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker10] [SMB] Received NTLM Type3/Authenticate -_ _[Type3:,LM:000000000000000000000000000000000000000000000000,NTLM:983c5b6f1df38689feedf59e3484c544010100000000000050fe1721923cd501df73f420ab622565000000000200080041004c00460036000100080041004c00460036000400080061006c00660036000300080061006c00660036000700080050fe1721923cd50106000400020000000800300030000000000000000100000000200000092cf0f5536f960c5b50ca4f52d99ef22f89929d511bfef8de964074b068f67f0a001000000000000000000000000000000000000900240063006900660073002f0061006c00660036002e006600690062006f002e0063006f006d00000000000000000000000000,Dom:ACME,User:topcat,Wks:7B,SessKey:9851b08d92e440ef1e0893539e3e9835,Flags:0x62888015]
 2019-07-17 14:23:59,570  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker10] [SMB] Signing required/SPNEGO, saved Type3
 2019-07-17 14:24:00,653  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker10] [SMB] User does not exist, topcat
 2019-07-17 14:24:00,663  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker10] [T1:2] Error processing security blob - org.alfresco.error.AlfrescoRuntimeException: 06170019 Exception in Transaction.
 2019-07-17 14:24:00,664  ERROR [org.alfresco.fileServersNG] [FileSrvWorker10] Error from JFileServer
 org.alfresco.error.AlfrescoRuntimeException: 06170019 Exception in Transaction._
        _at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:536)_
        _at org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator.doInTransaction(AlfrescoSMBAuthenticator.java:815)_
        _at org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator.processSecurityBlobInTransaction(AlfrescoSMBAuthenticator.java:832)_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.processSecurityBlob(EnterpriseSMBAuthenticator.java:767)_
        _at org.filesys.smb.server.a.e.b(Unknown Source)
        at org.filesys.smb.server.a.e.runProtocol(Unknown Source)
        at org.filesys.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1265)
        at org.filesys.smb.server.nio.NIOSMBThreadRequest.runRequest(NIOSMBThreadRequest.java:130)
        at org.filesys.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:136)
        at java.lang.Thread.run(Thread.java:748)_
_Caused by: org.filesys.smb.server.SMBSrvException: Access denied_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.doNTLMv2Logon(EnterpriseSMBAuthenticator.java:1596)_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.doNtlmsspSessionSetup(EnterpriseSMBAuthenticator.java:991)_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.doSpnegoSessionSetup(EnterpriseSMBAuthenticator.java:1078)_
        _at org.filesys.server.auth.EnterpriseSMBAuthenticator.processSecurityBlobInternal(EnterpriseSMBAuthenticator.java:811)_
        _at org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator$4.execute(AlfrescoSMBAuthenticator.java:838)_
        _at
org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator$4.execute(AlfrescoSMBAuthenticator.java:833)_
        _at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)_
        _... 9 more
2019-07-17 14:24:00,691  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker11] Error during packet receive, closing session sess=T1, addr=10.0.10.26 ex=Connection reset by peer
 2019-07-17 14:24:00,696  ERROR [org.alfresco.fileServersNG] [FileSrvWorker11] java.io.IOException: Connection reset by peer_


= fileServersNG startup when authentication chain is disabled;

2019-07-17 14:11:25,620  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Starting 'fileserversng-v61' subsystem, ID: [fileserversng-v61, default]
 Java config name: null
Native config name: /etc/krb5.conf
Loaded from native config
>>> KeyTabInputStream, readName(): ACME.COM
>>> KeyTabInputStream, readName(): smb
>>> KeyTabInputStream, readName(): alf6.ACME.COM
>>> KeyTab: load() entry length: 85; type: 18
>>> KeyTabInputStream, readName(): ACME.COM
>>> KeyTabInputStream, readName(): smb
>>> KeyTabInputStream, readName(): alf6.ACME.COM
>>> KeyTab: load() entry length: 69; type: 17
>>> KeyTabInputStream, readName(): ACME.COM
>>> KeyTabInputStream, readName(): smb
>>> KeyTabInputStream, readName(): alf6.ACME.COM
>>> KeyTab: load() entry length: 69; type: 23
>>> KeyTabInputStream, readName(): ACME.COM
>>> KeyTabInputStream, readName(): smb
>>> KeyTabInputStream, readName(): alf6.ACME.COM
>>> KeyTab: load() entry length: 61; type: 3
>>> KeyTabInputStream, readName(): ACME.COM
>>> KeyTabInputStream, readName(): smb
>>> KeyTabInputStream, readName(): alf6.ACME.COM
>>> KeyTab: load() entry length: 61; type: 1
Looking for keys for: SMB/alf6.ACME.COM@ACME.COM
Added key: 1version: 2
Added key: 3version: 2
Added key: 23version: 2
Added key: 17version: 2
Added key: 18version: 2
>>> KdcAccessibility: reset
Looking for keys for: SMB/alf6.ACME.COM@ACME.COM
Added key: 1version: 2
Added key: 3version: 2
Added key: 23version: 2
Added key: 17version: 2
Added key: 18version: 2
default etypes for default_tkt_enctypes: 18 17 23 1 3 16 16.
>>> KrbAsReq creating message
>>> KrbKdcReq send: kdc=10.0.10.2 UDP:88, timeout=30000, number of retries =3, #bytes=153
>>> KDCCommunication: kdc=10.0.10.2 UDP:88, timeout=30000,Attempt =1, #bytes=153
>>> KrbKdcReq send: #bytes read=268
>>>Pre-Authentication Data:
         PA-DATA type = 2
         PA-ENC-TIMESTAMP
>>>Pre-Authentication Data:
         PA-DATA type = 16

>>>Pre-Authentication Data:
         PA-DATA type = 15

>>>Pre-Authentication Data:
         PA-DATA type = 19
         PA-ETYPE-INFO2 etype = 18, salt = ACME.COMsmbalf6, s2kparams = 0000: 00 00 10 00                                        ....

>>> KdcAccessibility: remove 10.0.10.2
>>> KDCRep: init() encoding tag is 126 req type is 11
>>>KRBError:
         sTime is Wed Jul 17 14:11:25 EAT 2019 1563361885000
         suSec is 737585
         error code is 25
         error Message is Additional pre-authentication required
         cname is SMB/alf6.ACME.COM@ACME.COM
         sname is krbtgt/ACME.COM@ACME.COM
         eData provided.
         msgType is 30
>>>Pre-Authentication Data:
         PA-DATA type = 2
         PA-ENC-TIMESTAMP
>>>Pre-Authentication Data:
         PA-DATA type = 16

>>>Pre-Authentication Data:
         PA-DATA type = 15

>>>Pre-Authentication Data:
         PA-DATA type = 19
         PA-ETYPE-INFO2 etype = 18, salt = ACME.COMsmbalf6, s2kparams = 0000: 00 00 10 00                                        ....

KRBError received: Need to use PA-ENC-TIMESTAMP/PA-PK-AS-REQ
KrbAsReqBuilder: PREAUTH FAILED/REQ, re-send AS-REQ
default etypes for default_tkt_enctypes: 18 17 23 1 3 16 16.
Looking for keys for: SMB/alf6.ACME.COM@ACME.COM
Added key: 1version: 2
Added key: 3version: 2
Added key: 23version: 2
Added key: 17version: 2
Added key: 18version: 2
Looking for keys for: SMB/alf6.ACME.COM@ACME.COM
Added key: 1version: 2
Added key: 3version: 2
Added key: 23version: 2
Added key: 17version: 2
Added key: 18version: 2
default etypes for default_tkt_enctypes: 18 17 23 1 3 16 16.
>>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
>>> KrbAsReq creating message
>>> KrbKdcReq send: kdc=10.0.10.2 UDP:88, timeout=30000, number of retries =3, #bytes=240
>>> KDCCommunication: kdc=10.0.10.2 UDP:88, timeout=30000,Attempt =1, #bytes=240
>>> KrbKdcReq send: #bytes read=1378
>>> KdcAccessibility: remove 10.0.10.2
Looking for keys for: SMB/alf6.ACME.COM@ACME.COM
Added key: 1version: 2
Added key: 3version: 2
Added key: 23version: 2
Added key: 17version: 2
Added key: 18version: 2
>>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
>>> KrbAsRep cons in KrbAsReq.getReply SMB/alf6.ACME.COM
2019-07-17 14:11:26,509  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [localhost-startStop-1] Logged on using principal SMB/alf6.ACME.COM@ACME.COM
 2019-07-17 14:11:26,509  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [localhost-startStop-1] Enabling mechTypes :-Kerberos5 MS-Kerberos5
 2019-07-17 14:11:26,510  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [localhost-startStop-1]  Enabling NTLMSSP
 2019-07-17 14:11:26,751  DEBUG [org.alfresco.fileServersNG] [localhost-startStop-1] *** JFileServer Enterprise edition licenced to FileSys.Org (Free Use/support@filesys.org/25)
 2019-07-17 14:11:26,751  DEBUG [org.alfresco.fileServersNG] [localhost-startStop-1] ***  For version 1.*
 2019-07-17 14:11:26,784  DEBUG [org.alfresco.fileServersNG] [SMB Server] [SMB] SMB Server ALF6 starting
 2019-07-17 14:11:26,795  DEBUG [org.alfresco.fileServersNG] [SMB Server] [SMB] Version 1.0.0, Java VM 25.212-b01, OS Linux, version 4.9.0-8-amd64
 2019-07-17 14:11:26,795  DEBUG [org.alfresco.fileServersNG] [SMB Server] [SMB] Using authenticator org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator - SPNEGO,NoNTLMv1,Kerberos=ACME.COM
 2019-07-17 14:11:26,795  DEBUG [org.alfresco.fileServersNG] [SMB Server] [SMB] Server timezone offset = 0hrs
 2019-07-17 14:11:26,796  DEBUG [org.alfresco.fileServersNG] [SMB Server] [SMB] Dialects enabled = [SMB 2.002,SMB 2.210,SMB 2.ANY]
 2019-07-17 14:11:26,796  DEBUG [org.alfresco.fileServersNG] [SMB Server] [SMB] Shares:

**Comment by FileSysOrg** [comment]
The error looks a bit different now, I see a 'user does not exist, topcat'. I don't think the current code will create new Alfresco users but that could be added, I think there was a config option to do that at some point in the past.

Looks like the client is doing a Kerberos logon now. Try adding an Alfresco user 'topcat' and see if that gets further.

**Comment by wclemo** [comment]
@FileSysOrg "topcat" is a domain user. The user is the one already logged in to the Windows client and that's why when I first try to open Alfresco smb share fileserverNG picks up that user (topcat).

 Topcat is able to login via Alfresco http share and webdav via Kerberos.

If I create the topcat user in Alfresco, hence an NTLM user won't there be a conflict with this Domain Kerberos user ?

**Comment by FileSysOrg** [comment]
After the Kerberos authentication stage is successful the authenticator will then try to map the user name from the Kerberos principal to an Alfresco user (actually an Alfresco Person), which is then used as the user context for the session.

It looks like the client is still using an NTLM logon, so it would need  an Alfresco user with the same password if you want single sign-on. The Kerberos logon was the server startup.

I also noticed that the server principal is using 'SMB/alf6.ACME.COM@ACME.COM', that should be 'cifs/...'.

**Comment by wclemo** [comment]
I have now replaced the SPN with cifs/....  and with this change am now getting a different error log that might be a bit encouraging in narrowing down to the issue. Below is the error.

_2019-07-17 18:53:26,494  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker19] Active sessions [10=10.0.10.26,]
 2019-07-17 18:53:26,564  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker21] [SMB] Process security blob=[SPNEGO secBlob=[offset=92,len=1514] Unicode, respBlob=null]
 **Search Subject for Kerberos V5 ACCEPT cred (CIFS/alf6.acme.com@ACME.COM**, sun.security.jgss.krb5.Krb5AcceptCredential)
2019-07-17 18:53:26,570  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker21] [SMB] Using OID MS Kerberos5 for NegTokenTarg
 2019-07-17 18:53:26,571  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker21] [SMB] Created NegTokenTarg using standard Krb5 API response
 2019-07-17 18:53:26,571  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker21] [SMB] **Logged on using Kerberos, user topcat**
 2019-07-17 18:53:26,571  DEBUG [auth.smb.AlfrescoSMBAuthenticator] [FileSrvWorker21] [SMB] **User topcat logged on  (type Normal)**
 2019-07-17 18:53:26,589  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker21] [T10:2] Error processing security blob - org.alfresco.repo.security.authentication.AuthenticationException: 06170027 **Could not find user by userName: to******
 2019-07-17 18:53:26,589  **ERROR [org.alfresco.fileServersNG] [FileSrvWorker21] Error from JFileServer
 org.alfresco.repo.security.authentication.AuthenticationException: 06170027 Could not find user by userName: to****_**
        _at org.alfresco.repo.security.authentication.AbstractAuthenticationComponent.setCurrentUserImpl(AbstractAuthenticationComponent.java:300)_
        _at org.alfresco.repo.security.authentication.AbstractAuthenticationComponent.access$0(AbstractAuthenticationComponent.java:257)_
       _at org.alfresco.repo.security.authentication.AbstractAuthenticationComponent$FixCurrentUserCallback.execute(AbstractAuthenticationComponent.java:552)_
...
_2019-07-17 18:53:26,597  DEBUG [org.alfresco.fileServersNG] [FileSrvWorker22] Error during packet receive, closing session sess=T10, addr=10.0.10.26 ex=Connection reset by peer
 2019-07-17 18:53:26,598  ERROR [org.alfresco.fileServersNG] [FileSrvWorker22] java.io.IOException: Connection reset by peer_

**Comment by FileSysOrg** [comment]
The Kerberos authentication went through ok but the mapping to the Alfresco account did not find a match. The Alfresco account is exactly the same name as the Kerberos user name, including case ?.

You could enable authenticator debug output by adding the following to the log3j.properties file :-

log4j.logger.org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator=debug

I'll setup a test here to try and reproduce the issue.

**Comment by FileSysOrg** [comment]
The only way I can generate that error is if there is not a matching user in the Alfresco users list.

You need an Alfresco user for the security context when requests are being run against that user, for permissions, quotas etc. WebDAV and other connections will all need to map to an Alfresco user.

The LDAP sync would create a set of users with the same user name as the AD user.

**Comment by FileSysOrg** [comment]
How are you adding the users ?, is the Alfresco data new or an update from an older version ?. I've seen some problems in the past depending on how users are added.

**Comment by FileSysOrg** [comment]
Could you send me your Alfresco configuration that you use for the LDAP users ?, I'll setup the same here and see what I can do to get around the problem.

You can send to my email at gk.spencer at filesys dot org if you prefer.

**Comment by wclemo** [comment]
Am glad to report that this issue was resolved fileserversng-v61.
