### ISSUE TITLE
unable to connect smb2/smb3

### ISSUE THREAD

**Issue by hi-ko** [FileSysOrg/fileServersNG-v61#3]
Maybe a simliar issue like #1 

same config works somehow with alfresco 6.0 and SMB2/SMB3 activated from a domain win7 client without kerberos activated on the alfresco side but not with alfresco 6.1.

On alfresco 6.1. only trying with smb1 is working.

log from working alfresco 6.0 installation:

````
2019-07-04 19:36:05,824 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Created session T1
2019-07-04 19:36:05,825 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Connection from /192.168.22.105:61585, handler=[SMB,TCP-SMB,ALL:1445], sess=T1
2019-07-04 19:36:05,825 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Waiting for new connection ...
2019-07-04 19:36:05,825 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Register session with request handler, handler=SMBRequestHandler_1, sess=T1
2019-07-04 19:36:05,833 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker20] [T1] Closing session due to exception
2019-07-04 19:36:05,835 ERROR [org.alfresco.fileServersNG] [FileSrvWorker20] Error from JFileServer
java.lang.NullPointerException
        at org.filesys.smb.server.SMBSrvSession.procSMBNegotiate(SMBSrvSession.java:1022)
        at org.filesys.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1244)
        at org.filesys.smb.server.nio.NIOSMBThreadRequest.runRequest(NIOSMBThreadRequest.java:130)
        at org.filesys.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:136)
        at java.lang.Thread.run(Thread.java:748)
2019-07-04 19:36:05,838 ERROR [org.alfresco.fileServersNG] [FileSrvWorker20] Error from JFileServer
java.lang.NullPointerException
        at org.filesys.smb.server.SMBSrvSession.procSMBNegotiate(SMBSrvSession.java:1022)
        at org.filesys.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1244)
        at org.filesys.smb.server.nio.NIOSMBThreadRequest.runRequest(NIOSMBThreadRequest.java:130)
        at org.filesys.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:136)
        at java.lang.Thread.run(Thread.java:748)
2019-07-04 19:37:09,979 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker8] Error during packet receive, closing session sess=T1, addr=192.168.22.105 ex=Connection reset by peer
2019-07-04 19:37:09,980 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker8] [SMB] Closed session 1, sessions=0
2019-07-04 19:37:09,981 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Request handler SMBRequestHandler_1 waiting for session ...
2019-07-04 19:37:09,983 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Created session T2
2019-07-04 19:37:09,984 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Connection from /192.168.22.105:61586, handler=[SMB,TCP-SMB,ALL:1445], sess=T2
2019-07-04 19:37:09,984 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Waiting for new connection ...
2019-07-04 19:37:09,984 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Register session with request handler, handler=SMBRequestHandler_1, sess=T2
2019-07-04 19:37:09,985 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker9] [T2] Closing session due to exception
2019-07-04 19:37:09,985 ERROR [org.alfresco.fileServersNG] [FileSrvWorker9] Error from JFileServer
java.lang.NullPointerException
        at org.filesys.smb.server.SMBSrvSession.procSMBNegotiate(SMBSrvSession.java:1022)
        at org.filesys.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1244)
        at org.filesys.smb.server.nio.NIOSMBThreadRequest.runRequest(NIOSMBThreadRequest.java:130)
        at org.filesys.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:136)
        at java.lang.Thread.run(Thread.java:748)
2019-07-04 19:37:09,985 ERROR [org.alfresco.fileServersNG] [FileSrvWorker9] Error from JFileServer
java.lang.NullPointerException
        at org.filesys.smb.server.SMBSrvSession.procSMBNegotiate(SMBSrvSession.java:1022)
        at org.filesys.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1244)
        at org.filesys.smb.server.nio.NIOSMBThreadRequest.runRequest(NIOSMBThreadRequest.java:130)
        at org.filesys.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:136)
        at java.lang.Thread.run(Thread.java:748)
2019-07-04 19:38:21,986 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker25] Error during packet receive, closing session sess=T2, addr=192.168.22.105 ex=Connection reset by peer
2019-07-04 19:38:21,986 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker25] [SMB] Closed session 2, sessions=0
2019-07-04 19:38:21,987 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Request handler SMBRequestHandler_1 waiting for session ...
2019-07-04 20:05:34,403 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Created session T3
2019-07-04 20:05:34,404 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Connection from /192.168.22.105:59610, handler=[SMB,TCP-SMB,ALL:1445], sess=T3
2019-07-04 20:05:34,405 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Waiting for new connection ...
2019-07-04 20:05:34,405 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Register session with request handler, handler=SMBRequestHandler_1, sess=T3
````

trying the same from the same win7 using the exact same config on alfresco 6.1 I can't connect.
"The mapped network drive could not be crated because the following error has occurred:
The specific serve cannot perform the requested operation"

in the server log:

````
2019-07-04 20:13:01,547 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Created session T5
2019-07-04 20:13:01,552 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Connection from /192.168.22.105:59614, handler=[SMB,TCP-SMB,ALL:1445], sess=T5
2019-07-04 20:13:01,553 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Waiting for new connection ...
2019-07-04 20:13:01,553 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Register session with request handler, handler=SMBRequestHandler_1, sess=T5
2019-07-04 20:13:01,555 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker19] Error during packet receive, closing session sess=T5, addr=192.168.22.105 ex=Connection reset by peer
2019-07-04 20:13:01,556 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker19] [SMB] Closed session 5, sessions=0
2019-07-04 20:13:01,557 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Request handler SMBRequestHandler_1 waiting for session ...
2019-07-04 20:13:01,558 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Created session T6
2019-07-04 20:13:01,558 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Connection from /192.168.22.105:59615, handler=[SMB,TCP-SMB,ALL:1445], sess=T6
2019-07-04 20:13:01,558 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Register session with request handler, handler=SMBRequestHandler_1, sess=T6
2019-07-04 20:13:01,558 DEBUG [org.alfresco.fileServersNG] [SMBConnectionsHandler] [SMB] Waiting for new connection ...
2019-07-04 20:13:01,563 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker21] Error during packet receive, closing session sess=T6, addr=192.168.22.105 ex=Connection reset by peer
2019-07-04 20:13:01,564 DEBUG [org.alfresco.fileServersNG] [FileSrvWorker21] [SMB] Closed session 6, sessions=0
2019-07-04 20:13:01,564 DEBUG [org.alfresco.fileServersNG] [SMBRequestHandler_1] [SMB] Request handler SMBRequestHandler_1 waiting for session ...
````

my config in alfresco-global.properties:
````
#-----------------------
# Enable the fileServersNG SMB and FTP servers
#-----------------------

# Path to the JFileServer licence file (to enable enterprise features)
#fileServersNG.licencePath=license/

# fileServersNG SMB server configuration
smb.enabled=true
smb.dialects=SMB2,SMB3
smb.sessionDebug=Socket

# Enable the use of asynchronous sockets/NIO code
smb.disableNIO=false
# Session timeout, in seconds. Defaults to 15 minutes, to match the default Windows client setting.
# If no I/O is received within that time the session is closed by the server
smb.sessionTimeout=900
# Can be mapped to non-privileged ports, then use firewall rules to forward requests from the standard ports
smb.tcpipSMB.port=1445
smb.netBIOSSMB.sessionPort=1139
smb.netBIOSSMB.namePort=1137
smb.netBIOSSMB.datagramPort=1138
# Optional WINS server primary and secondary IP addresses. Ignored if autoDetectEnabled=true
smb.WINS.autoDetectEnabled=true
# smb.WINS.primary=1.2.3.4
# smb.WINS.secondary=5.6.7.8
smb.pseudoFiles.enabled=false
smb.pseudoFiles.shareURL.enabled=false
#smb.terminalServerList=
# Should only be changed when using Terminal Server clients
#smb.maximumVirtualCircuitsPerSession=16

# fileServersNG FTP server configuration
ftpng.enabled=false
ftp.port=1121
ftp.sessionDebug=File,Search,Error,DataPort,Directory
````

**Comment by hi-ko** [comment]
Other strange thing which also does apply to the 6.0 version:
when switching config from 

`smb.dialects=SMB1` to `smb.dialects=SMB2,SMB3`

I need to reboot the win7 system before I get a successful connection.
Maybe windows is caching the smb version?

**Comment by hi-ko** [comment]
indeed same issue as #1 
if I set 
`smb.useSPNEGO=true`
in alfresco-global.properties I can connect

Thanks a lot to migrate you implementation to 6.1!
